on:
  schedule:
    - cron:  '30 7 * * *'

name: deploy

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: r-lib/actions/setup-r@v1

      - name: Install
        run: |
          brew install pandoc
          Rscript -e 'install.packages(c("jsonlite", "forecast", "rvest", "xml2", "leaflet", "htmlwidgets"))'

      - name: Run scripts
        run: |
          Rscript update-global.R
          Rscript update-canada.R
          Rscript update-alberta.R

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
          clean: false # Automatically remove deleted files from the deploy branch
